### ISSUE TITLE
The `align` property is stripped from `td` elements, breaking styling

### ISSUE THREAD

**Issue by jorroll** [rehypejs/rehype-react#47]
### Initial checklist

- [X] I read the [support docs](https://github.com/rehypejs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/rehypejs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/rehypejs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Arehypejs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

rehype-react 7.1.2

### Link to runnable example

https://stackblitz.com/edit/react-ts-whdlcz?file=App.tsx

### Steps to reproduce

Open [this stackblitz link](https://stackblitz.com/edit/react-ts-whdlcz?file=App.tsx) and inspect the `<td />` element in the dom. Notice how it's properties don't match the input HTML. It appears as though `align="center"` is being converted to `style="text-align: center;"`, which isn't equivalent. I suspect that this was an intentional decision because the `align` property is deprecated on `td` elements and the [MDN docs suggest](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/td) that it can be replaced with `text-align: center` css, but as previously mentioned the two are not equivalent (regardless of what MDN says). Here is a video demonstrating how converting `align="center"` to `text-align: center` breaks the CSS styling in an email.
- https://www.loom.com/share/95759a08773041b2afea63791ff499eb

### Expected behavior

I expect the output JSX to match the input HTML. Specifically, I expect input HTML of `<td align="center"></td>` to be output as JSX `<td align="center" />`.

### Actual behavior

The output JSX does not match the input HTML. Specifically, input HTML of `<td align="center"></td>` is output as JSX `<td style="text-align: center;" />`.

### Runtime

Node v16

### Package manager

yarn 1

### OS

macOS

### Build and bundle tools

Vite

**Comment by wooorm** [comment]
Hi!

They are not the same but they are equivalent in React as far as I am aware.
The main difference is that React does not support align, which is why https://www.npmjs.com/package/@mapbox/hast-util-table-cell-style is used.

For you actual use case:
- If you don’t need to process HTML, you can use `dangerouslySetInnerHTML`
- If you do need to parse HTML, and use this in browsers (and node), you might want to use  https://github.com/syntax-tree/hast-util-from-html-isomorphic
- If you are looking for a modern replacement of the internally used utility, see https://github.com/syntax-tree/hast-util-to-jsx-runtime. I haven‘t had the time to move this project to that. It doesn’t yet handle `align` like this project does. But it might in the future, with an option

**Comment by wooorm** [comment]
> I believe [modern React supports the passthrough of any property](https://legacy.reactjs.org/docs/dom-elements.html#all-supported-html-attributes)

Where does it say that on that page?

> modern React

Do you have a source?

> are not equivalent.

They are equivalent according to the HTML spec. The HTML spec specifies the default style sheet that browsers use. Which maps these attributes to CSS: https://html.spec.whatwg.org/multipage/rendering.html#tables-2.

**Comment by jorroll** [comment]
> > Would you accept a PR to add an option to disable the problematic behavior?
>
> Sure

# 👍 

> > I believe [modern React supports the passthrough of any property](https://legacy.reactjs.org/docs/dom-elements.html#all-supported-html-attributes)
> 
> Where does it say that on that page?

It's at the very bottom:

<img width="626" alt="Screenshot 2023-04-12 at 12 52 28 PM" src="https://user-images.githubusercontent.com/12599934/231559917-1318f2bd-2b19-4df9-8f71-9484eea231bc.png">

I updated [the demo](https://stackblitz.com/edit/react-ts-whdlcz?file=App.tsx) to include an example of this. 

<img width="603" alt="Screenshot 2023-04-12 at 1 08 21 PM" src="https://user-images.githubusercontent.com/12599934/231560097-faa901cb-c8aa-41c6-8d6d-84a6e8cc7d7b.png">

`<td youcanactuallyaddanycustompropanditwillberetainedintheoutput="custom"></td>` is included in the output rendered by React. The demo shows this using React 18, but I've also tested it in React 17. [This React documentation page](https://legacy.reactjs.org/docs/dom-elements.html#all-supported-html-attributes) leads me to believe that this behavior has existed since React 16.

> I’ve changed behavior in these packages several times because it didn‘t emit warnings in production build (stackblitz maybe?). And then after a month someone mentioned that it actually still emits warnings. So I’d rather not do the same again.

My fork doesn't appear to be causing any React warnings. I'll note that in the current (non-forked) package I do see warnings like the following:

<img width="917" alt="Screenshot 2023-04-12 at 1 21 55 PM" src="https://user-images.githubusercontent.com/12599934/231563000-6235af89-7b73-4ff8-9487-0c2839340694.png">

These warnings also exist in my forked version of the package, but there are no new warnings.

> I guess the thing here, with emails, is the bit about **and to align descendants to the center** in the HTML spec.

Seems like a reasonable hypothesis. Ultimately I'm not too concerned with why. Even if Chrome wasn't following the spec, I'd still defer to whatever Chrome did (obviously this won't apply to everyone--hence making the behavior togglable seems prudent in this case).

> Interesting! Thanks for the video! What type of tool is that, which you are showing?

The video was taken with a tool called [Loom](https://www.loom.com/), the "correct" behavior was demonstrated with a gmail client called [superhuman](https://superhuman.com/) (the Gmail web app also renders the content the "correct" way), the problematic behavior was shown in an unpublished email client I'm working on.

Thanks!

**Comment by wooorm** [comment]
> is included in the output 

As far as I am aware, the reason this exists isn’t about whether `align` is included in the output.
It’s I believe because it emits warnings. And because humans should not use `align`.

For the warnings, for lowercase attributes, it doesn’t seem to happen looking here: https://github.com/facebook/react/blame/b6c423daadaa35da3f34048628df9635505eecb1/packages/react-dom/src/shared/ReactDOMUnknownPropertyHook.js (line 155) for 6 years.

> Ultimately I'm not too concerned with why

Understandable, but I am: because if your tool is broken, that’s where the fix should go, not here.

> the "correct" behavior was demonstrated with a gmail client called

I particularly mean the tool that does not align things if `text-align` is present. Because that should align things? What is previewing those emails? Superhuman?

Do you have cells in cells (in more cells)? Then I think it’s the “align descendants to the center” thing that the spec describes.

**Comment by jorroll** [comment]
Sidenote: if you haven't had the misfortune of working with emails before, it's very common for emails to be rendered with HTML like it's 1995.

**Comment by wooorm** [comment]
> Here are two emails exhibiting the behavior that you can inspect.

So this is indeed table cells (in tables) in table cells.
The second example does not exhibit your bug from what I can see, because the table itself also has `align=center`, which aligns itself in the middle.
The first example doesn’t: `text-align: center` on the outer cell does not apply to the table, so the table is flush left.
In the second example, I can remove all `text-align:center`s and it works fine. But removing `align="center"` on the table, or setting `display: block` on it, moves it left.

> Sidenote: if you haven't had the misfortune of working with emails before, it's very common for emails to be rendered with HTML like it's 1995.

Yeah, I just wonder how much I should care about things that are removed from the HTML spec.
